### ISSUE TITLE
[project-item] add a bigger variant of the ProjectItem in the portfolio archive page

### ISSUE THREAD

**Issue by Akiletour** [inrage/inrage#8]
On the portfolio page, all projects items are bigger than on the related project.

## TODO

- [x] Add a bigger size for the images + text
- [x] Edit the ProjectItem components to do it
- [x] Set the smaller size by default
- [x] Use this bigger ProjectItem component on the portfolio and taxonomy (support) page.

## Preview in production

![CleanShot 2021-12-29 at 12 27 25](https://user-images.githubusercontent.com/1524422/147657669-8037644b-e8a1-4214-902f-0515800335ba.png)
